import { useState, useEffect } from "react";
import { useMutation, useQuery, useAction } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";
import { toast } from "sonner";

interface ChatPanelProps {
  selectedConversationId: Id<"conversations"> | null;
  onConversationSelect: (id: Id<"conversations">) => void;
  businessContext: {
    businessName: string;
    websiteUrl: string | null;
  } | null;
}

export function ChatPanel({ selectedConversationId, onConversationSelect, businessContext }: ChatPanelProps) {
  const [message, setMessage] = useState("");
  const [websiteUrl, setWebsiteUrl] = useState("");
  const [setupStep, setSetupStep] = useState<"website-url" | "chat">("chat");
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const conversations = useQuery(api.conversations.getConversations) || [];
  const selectedConversation = useQuery(
    api.conversations.getConversation,
    selectedConversationId ? { conversationId: selectedConversationId } : "skip"
  );

  const createConversation = useMutation(api.conversations.createConversation);
  const addMessage = useMutation(api.conversations.addMessage);
  const generateSpec = useAction(api.ai.generateWebsiteSpec);

  // Auto-generate spec when business context is provided with website URL
  useEffect(() => {
    if (businessContext && businessContext.websiteUrl && !hasAutoGenerated && !selectedConversationId) {
      setHasAutoGenerated(true);
      handleAutoGenerate();
    } else if (businessContext && !businessContext.websiteUrl && !selectedConversationId) {
      setSetupStep("website-url");
      setWebsiteUrl("");
    }
  }, [businessContext, hasAutoGenerated, selectedConversationId]);

  const handleAutoGenerate = async () => {
    if (!businessContext || !businessContext.websiteUrl) return;

    try {
      setIsGenerating(true);
      setSetupStep("chat");
      toast.info("Generating specification...");

      const defaultMessage = `Create a comprehensive website specification for ${businessContext.businessName}`;
      const title = businessContext.businessName;

      const conversationId = await createConversation({
        title,
        initialMessage: defaultMessage,
        businessName: businessContext.businessName,
        websiteUrl: businessContext.websiteUrl,
      });

      onConversationSelect(conversationId);

      // Generate AI response with all parallel data fetching
      await generateSpec({
        conversationId,
        userInput: defaultMessage,
      });

      setIsGenerating(false);
      toast.success("Website specification generated!");
    } catch (error) {
      console.error("Error generating specification:", error);
      toast.error("Failed to generate specification");
      setIsGenerating(false);
    }
  };

  const handleSendMessage = async () => {
    if (!message.trim()) return;

    try {
      setIsGenerating(true);
      let conversationId = selectedConversationId;

      if (!conversationId) {
        // Create new conversation with business context
        const title = message.slice(0, 50) + (message.length > 50 ? "..." : "");
        conversationId = await createConversation({
          title,
          initialMessage: message,
          businessName: businessContext?.businessName || undefined,
          websiteUrl: businessContext?.websiteUrl || websiteUrl.trim() || undefined,
        });
        onConversationSelect(conversationId);
      } else {
        // Add message to existing conversation
        await addMessage({
          conversationId,
          role: "user",
          content: message,
        });
      }

      // Generate AI response
      await generateSpec({
        conversationId,
        userInput: message,
      });

      setMessage("");
      toast.success("Website specification generated!");
    } catch (error) {
      console.error("Error sending message:", error);
      toast.error("Failed to generate specification");
    } finally {
      setIsGenerating(false);
    }
  };


  const handleContinueWithWebsite = async () => {
    if (!websiteUrl.trim()) {
      toast.error("Please enter a website URL");
      return;
    }

    try {
      setIsGenerating(true);
      setSetupStep("chat");
      toast.info("Generating specification...");

      const defaultMessage = businessContext?.businessName
        ? `Create a comprehensive website specification for ${businessContext.businessName}`
        : "Create a comprehensive website specification for this business";
      const title = businessContext?.businessName || websiteUrl.slice(0, 50);

      const conversationId = await createConversation({
        title,
        initialMessage: defaultMessage,
        businessName: businessContext?.businessName || undefined,
        websiteUrl: websiteUrl.trim(),
      });

      onConversationSelect(conversationId);

      // Generate AI response with all parallel data fetching
      await generateSpec({
        conversationId,
        userInput: defaultMessage,
      });

      setIsGenerating(false);
      toast.success("Website specification generated!");
    } catch (error) {
      console.error("Error generating specification:", error);
      toast.error("Failed to generate specification");
      setIsGenerating(false);
    }
  };

  const handleSkipToChat = () => {
    setSetupStep("chat");
  };


  return (
    <div className="flex flex-col h-full">
      {/* Conversation List */}
      <div className="border-b border-gray-200 p-4">
        <h3 className="text-lg font-semibold mb-4">Conversations</h3>
        <div className="space-y-2 max-h-32 overflow-y-auto">
          {conversations.map((conv) => (
            <button
              key={conv._id}
              onClick={() => onConversationSelect(conv._id)}
              className={`w-full text-left p-2 rounded text-sm transition-colors ${
                selectedConversationId === conv._id
                  ? "bg-primary text-white"
                  : "bg-gray-100 hover:bg-gray-200"
              }`}
            >
              {conv.title}
            </button>
          ))}
        </div>
      </div>

      {/* Chat Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {selectedConversation?.messages.map((msg, index) => (
          <div
            key={index}
            className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-[80%] p-3 rounded-lg ${
                msg.role === "user"
                  ? "bg-primary text-white"
                  : "bg-gray-100 text-gray-800"
              }`}
            >
              <div className="text-sm">{msg.content}</div>
              <div className="text-xs opacity-70 mt-1">
                {new Date(msg.timestamp).toLocaleTimeString()}
              </div>
            </div>
          </div>
        ))}
        {isGenerating && (
          <div className="flex justify-start">
            <div className="bg-gray-100 text-gray-800 p-3 rounded-lg">
              <div className="flex items-center space-x-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary"></div>
                <span className="text-sm">Generating specification...</span>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Message Input / Setup Form */}
      <div className="border-t border-gray-200 p-4">
        {/* Business Setup - Only show for new conversations */}
        {!selectedConversationId && (
          <>
            {/* Website URL Input (if website not found on landing page) */}
            {setupStep === "website-url" && (
              <div className="mb-3 space-y-3">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Website URL
                  </label>
                  <input
                    type="text"
                    value={websiteUrl}
                    onChange={(e) => setWebsiteUrl(e.target.value)}
                    placeholder="e.g., https://www.example.com"
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
                    disabled={isGenerating}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && websiteUrl.trim()) {
                        e.preventDefault();
                        handleContinueWithWebsite();
                      }
                    }}
                  />
                  <p className="mt-1 text-xs text-gray-500">
                    We'll scrape this website and generate SEO analysis
                  </p>
                </div>
                <div className="flex space-x-2">
                  <button
                    onClick={handleContinueWithWebsite}
                    disabled={!websiteUrl.trim() || isGenerating}
                    className="flex-1 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary-hover transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {isGenerating ? (
                      <div className="flex items-center justify-center space-x-2">
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                        <span>Generating...</span>
                      </div>
                    ) : (
                      "Continue"
                    )}
                  </button>
                  <button
                    onClick={handleSkipToChat}
                    disabled={isGenerating}
                    className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Skip
                  </button>
                </div>
              </div>
            )}
          </>
        )}

        {/* Chat Interface - Show when conversation selected or setup complete */}
        {(selectedConversationId || setupStep === "chat") && (
          <div className="flex space-x-2">
            <textarea
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder="Describe your business and what you want for your website..."
              className="flex-1 p-3 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"
              rows={3}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSendMessage();
                }
              }}
            />
            <button
              onClick={handleSendMessage}
              disabled={!message.trim() || isGenerating}
              className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary-hover transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Send
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
